# Config version
version: 0.3.0

# HTML Head settings
html:
  title: DxMorgan | Testeo

# Main container settings
main:
  title: Dexter Morgan 

# Blocks list
blocks:
  - title: Telegram 
    icon: telegram
    url: https://t.me/dxmorgan

#  - title: Discord
#    icon: discord
#    url: https://discord.lacrypta.com.ar

#  - title: Quiero participar!
#    icon: voluntary
#    url: https://docs.google.com/forms/d/e/1FAIpQLSfMM_fDXrBVlxujPy4yhYRuhHWrtPSvoD8QRCKuHzZXgsFFzg/viewform

  - title: Github
    icon: github
    url: https://github.com/chelodxmg/

  - title: Twitter
    icon: twitter
    url: https://twitter.com/chelodxmg

  - title: PlayFC Movies
    icon: url
    url: t.me/playfc

  - title: WhatsApp
    icon: whatsapp
    url: https://api.whatsapp.com/send/?phone=%2B541128073054&text=Hola+que+tal&type=phone_number&app_absent=0
